import type { Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";

const config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./index.html",
  ],
  prefix: "",
  theme: {
    container: {
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", ...fontFamily.sans],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "blocks-btn-secondary": "hsl(var(--blocks-secondary-300))",
        "high-emphasis": "hsl(var(--high-emphasis))",
        "medium-emphasis": "hsl(var(--medium-emphasis))",
        "low-emphasis": "hsl(var(--low-emphasis))",
        "border-default": "hsl(var(--border-default))",
        "border-medium-emphasis": "hsl(var(--border-medium-emphasis))",
        "blocks-primary-25": "hsl(var(--blocks-primary-25))",
        "blocks-primary-50": "hsl(var(--blocks-primary-50))",
        "blocks-primary-100": "hsl(var(--blocks-primary-100))",
        "blocks-primary-200": "hsl(var(--blocks-primary-200))",
        "blocks-primary-300": "hsl(var(--blocks-primary-300))",
        "blocks-primary-400": "hsl(var(--blocks-primary-400))",
        "blocks-primary-500": "hsl(var(--blocks-primary-500))",
        "blocks-primary-600": "hsl(var(--blocks-primary-600))",
        "blocks-primary-700": "hsl(var(--blocks-primary-700))",
        "blocks-primary-800": "hsl(var(--blocks-primary-800))",
        "blocks-primary-900": "hsl(var(--blocks-primary-900))",
        "blocks-primary-shades-100": "hsl(var(--blocks-primary-shades-100))",
        "blocks-primary-shades-200": "hsl(var(--blocks-primary-shades-200))",
        "blocks-primary-shades-300": "hsl(var(--blocks-primary-shades-300))",
        "blocks-secondary-50": "hsl(var(--blocks-secondary-50))",
        "blocks-secondary-100": "hsl(var(--blocks-secondary-100))",
        "blocks-secondary-200": "hsl(var(--blocks-secondary-200))",
        "blocks-secondary-300": "hsl(var(--blocks-secondary-300))",
        "blocks-secondary-400": "hsl(var(--blocks-secondary-400))",
        "blocks-secondary-500": "hsl(var(--blocks-secondary-500))",
        "blocks-secondary-600": "hsl(var(--blocks-secondary-600))",
        "blocks-secondary-700": "hsl(var(--blocks-secondary-700))",
        "blocks-secondary-800": "hsl(var(--blocks-secondary-800))",
        "blocks-secondary-900": "hsl(var(--blocks-secondary-900))",
        "surface-app": "hsl(var(--surface-app))",
        error: "hsl(var(--error))",
        success: "hsl(var(--success))",
        "neutral-50": "hsl(var(--neutral-50))",
        "neutral-200": "hsl(var(--neutral-200))",
        "neutral-300": "hsl(var(--neutral-300))",
        "warning-50": "hsl(var(--warning-50))",
        "warning-100": "hsl(var(--warning-100))",
        "warning-200": "hsl(var(--warning-200))",
        "warning-300": "hsl(var(--warning-300))",
        "warning-400": "hsl(var(--warning-400))",
        "warning-500": "hsl(var(--warning-500))",
        "warning-600": "hsl(var(--warning-600))",
        "warning-700": "hsl(var(--warning-700))",
        "warning-800": "hsl(var(--warning-800))",
        "warning-900": "hsl(var(--warning-900))",
        "base-warning": "hsl(var(--base-warning))",
        "icon-warning": "hsl(var(--icon-warning))",
        "chart-purple": "hsl(var(--chart-purple))",
        "chart-purple-light": "hsl(var(--chart-purple-light))",
        "chart-magenta": "hsl(var(--chart-magenta))",
        "chart-yellow": "hsl(var(--chart-yellow))",
        "chart-red": "hsl(var(--chart-red))",
        "chart-blue": "hsl(var(--chart-blue))",
        "chart-orange": "hsl(var(--chart-orange))",
        "chart-brown-gray": "hsl(var(--chart-brown-gray))",
        "blocks-error-50": "var(--blocks-error-50)",
        "blocks-error-100": "var(--blocks-error-100)",
        "blocks-error-800": "var(--blocks-error-800)",
        "avatar-surface-default": "var(--avatar-surface-default)",
        "avatar-text-high-emphasis": "var(--avatar-text-high-emphasis)",
        "base-error": "var(--base-error)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
