import {
  BadgePercent,
  Building2,
  CirclePlus,
  CreditCard,
  FileText,
  FlaskConical,
  Home,
  Layers,
  Package,
  ReceiptText,
  Settings2,
  WalletCards,
  Wand2,
} from "lucide-react";
import { Menu } from "@/models/menu-models";

export const navigationMenus: Menu[] = [
  {
    id: "overview-project",
    type: "menu",
    name: "Overview",
    path: "/app/dashboard",
    icon: Home,
  },
  {
    type: "separator",
    id: "separator-overview",
  },
  {
    id: "environments",
    type: "menu",
    name: "Environments",
    path: "/app/project/environments",
    icon: Package,
  },
  {
    id: "payment",
    type: "menu",
    name: "Payments",
    path: "/app/payment",
    icon: CreditCard,
    children: [
      {
        id: "payment-create",
        type: "menu",
        name: "Create Payment",
        path: "/app/payment/create",
        icon: CirclePlus,
      },
      {
        id: "payment-list",
        type: "menu",
        name: "Payment List",
        path: "/app/payment/list",
        icon: ReceiptText,
      },
      {
        id: "payment-methods",
        type: "menu",
        name: "Saved Cards",
        path: "/app/payment/cards",
        icon: WalletCards,
      },
      {
        id: "payment-providers",
        type: "menu",
        name: "Payment Providers",
        path: "/app/payment/providers",
        icon: Settings2,
      },
    ],
  },
  {
    id: "subscription",
    type: "menu",
    name: "Subscriptions",
    path: "/app/subscription/plans",
    icon: Layers,
    children: [
      {
        id: "subscription-plans",
        type: "menu",
        name: "Plans",
        path: "/app/subscription/plans",
        icon: Layers,
      },
      {
        id: "subscription-discounts",
        type: "menu",
        name: "Discounts",
        path: "/app/subscription/discounts",
        icon: BadgePercent,
      },
      {
        id: "subscription-invoices",
        type: "menu",
        name: "Invoices",
        path: "/app/subscription/invoices",
        icon: FileText,
      },
      {
        id: "subscription-billing-profile",
        type: "menu",
        name: "Billing profile",
        path: "/app/subscription/billing-profile",
        icon: ReceiptText,
      },
      {
        id: "subscription-merchant-profile",
        type: "menu",
        name: "Merchant profile",
        path: "/app/subscription/merchant-profile",
        icon: Building2,
      },
      {
        id: "subscription-simulation",
        type: "menu",
        name: "Simulation",
        path: "/app/subscription/simulation",
        icon: FlaskConical,
      },
    ],
  },
  {
    id: "magic-url",
    type: "menu",
    name: "Magic URL",
    path: "/app/magic-url",
    icon: Wand2,
  },
];
