<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.Graph" />
    <PackageReference Include="Microsoft.Kiota.Abstractions" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="SeliseBlocks.Genesis.OS" />
  </ItemGroup>

</Project>
