<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	  <PackageReference Include="Azure.Identity" />
	  <PackageReference Include="Azure.ResourceManager.ServiceBus" />
	  <PackageReference Include="FluentValidation" />
	  <PackageReference Include="SeliseBlocks.MailDriver" />
	  <PackageReference Include="SeliseBlocks.StorageDriver" />
	  <PackageReference Include="SixLabors.Fonts" />
    <PackageReference Include="SSH.NET" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Captcha.DomainService\Captcha.DomainService.csproj" />
    <ProjectReference Include="..\Iam.DomainService\Iam.DomainService.csproj" />
  </ItemGroup>

  

</Project>
