export const blankTemplate = {
  page: {
    title: "",
    description: "",
    template: {
      name: "template-base",
      type: "basic",
      version: "0.0.1",
    },
    body: {
      type: "mailup-bee-page-proprerties",
      container: {
        style: {
          "background-color": "#FFFFFF",
        },
      },
      content: {
        style: {
          "font-family": "Arial, 'Helvetica Neue', Helvetica, sans-serif",
          color: "#000000",
        },
        computedStyle: {
          linkColor: "#0068A5",
          messageBackgroundColor: "transparent",
          messageWidth: "500px",
        },
      },
    },
    rows: [
      {
        type: "one-column-empty",
        container: {
          style: {
            "background-color": "transparent",
          },
        },
        content: {
          style: {
            "background-color": "transparent",
            color: "#000000",
            width: "500px",
          },
        },
        columns: [
          {
            "grid-columns": 12,
            modules: [
              {
                type: "mailup-bee-newsletter-modules-empty",
                descriptor: {},
              },
            ],
            style: {
              "background-color": "transparent",
              "padding-top": "5px",
              "padding-right": "0px",
              "padding-bottom": "5px",
              "padding-left": "0px",
              "border-top": "0px dotted transparent",
              "border-right": "0px dotted transparent",
              "border-bottom": "0px dotted transparent",
              "border-left": "0px dotted transparent",
            },
          },
        ],
      },
    ],
  },
  comments: {},
  Plan: "Startup",
  CoEditingEnterprise: false,
  Uid: "selise-ecap-bee-plugin-uid-dev-stg",
  RoleHash: "",
  Role: "",
  CustomCss: "",
  AppSettings: {
    TopBarEnabled: false,
    TopBarLogoEnabled: true,
    TopBarSaveEnabled: true,
    TopBarAutoSaveEnabled: true,
    TopBarPreviewEnabled: true,
    TopBarSendTestEnabled: true,
    TopBarSaveAsTemplateEnabled: true,
    TopBarHelpEnabled: true,
    TopBarCustomHelpUrl: "https://docs.beefree.io",
    LinkedStorageEnabled: false,
    LinkedStorageClientId: "",
    ConfirmOverwriteModalEnabled: false,
    HtmlBlockEnabled: true,
    VideoBlockEnabled: true,
    FreePhotosEnabled: true,
    FreeVideosEnabled: false,
    EditImageEnabled: false,
    CommentingEnabled: false,
    ReverseStackOnMobileEnabled: false,
    HistoryEnabled: false,
    SaveRowsEnabled: false,
    SanitizeHTMLDisabled: false,
    AnalyticsDisabled: false,
    ImportExternalAssetsEnabled: false,
    BackgroundImageEnabled: false,
    DynamicImageEnabled: false,
    BackgroundVideoEnabled: false,
    BackgroundVideoPickerButtonEnabled: false,
    RowDisplayConditionEnabled: false,
    DoNotStackOnMobileEnabled: false,
    HideContentOnMobileEnabled: false,
    CustomIconsEnabled: false,
    IconsBlockEnabled: true,
    MenuBlockEnabled: true,
    FormBlockEnabled: true,
    CarouselBlockEnabled: false,
    FaviconEnabled: false,
    BodyBackgroundImageEnabled: false,
    TitleEnabled: false,
    DescriptionEnabled: false,
    LanguageEnabled: false,
    HeadingBlockEnabled: false,
    MultiDeviceStageEnabled: false,
    MergeTagsEnhancementsEnabled: false,
    MergeTagsPreviewEnabled: false,
    EmojiTextToolbarEnabled: false,
    SpacerBlockEnabled: false,
    ListBlockEnabled: false,
    ParagraphBlockEnabled: false,
    TextBlockEnabled: true,
    DarkModePreviewEnabled: false,
    RowRoundedCornersEnabled: true,
    RowVerticalAlignmentEnabled: false,
    MultiLanguageTemplateEnabled: false,
    SubjectEnabled: false,
    PreheaderEnabled: false,
    TableBlockEnabled: false,
    CardsStyleWidgetsEnabled: false,
    ImageRoundedCornersEnabled: false,
    UploadLimitInBytes: 20971520,
    FSPMoveEnabled: false,
    CloudStorageService: true,
    NewBumperEnabled: true,
    HostedSavedRowsEnabled: false,
    NewCoeditEnabled: false,
    OutlookButtonEnabled: false,
  },
  AppStyles: {},
  Permissions: {
    CanLockRows: false,
    CanLockModules: false,
    CanEditLockedRows: false,
    CanEditLockedModules: false,
    CanSelectDisplayConditions: true,
    CanEditDisplayConditions: true,
    CanRemoveDisplayConditions: true,
  },
  AddOns: [],
  CustomAddOns: [],
  CustomAssets: [],
};
