<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-Worker-d76f990a-b305-46d4-9d8a-6be392ee733f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Utility.DomainService\Utility.DomainService.csproj" />
    <ProjectReference Include="..\Mail.DomainService\Mail.DomainService.csproj" />
    <ProjectReference Include="..\Notification.DomainService\Notification.DomainService.csproj" />
  </ItemGroup>
</Project>
