<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Version>4.0.0</Version>
		<PackageId>SeliseBlocks.MailDriver.OS</PackageId>
		<Authors>SeliseBlocks</Authors>
		<Company>SeliseBlocks</Company>
		<Description>Blocks Mail Driver</Description>
		<IncludeBuildOutput>true</IncludeBuildOutput>
    	<IncludeOutputAssemblies>true</IncludeOutputAssemblies>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>Genesis, BlocksGenesis, SeliseBlocksGenesis, Email, Mail, Driver</PackageTags>
		<RepositoryUrl>https://github.com/SELISEdigitalplatforms/blocks-utilities</RepositoryUrl>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
   		<None Include="$(OutputPath)Mail.DomainService.dll" Pack="true" PackagePath="lib/net10.0/" />
	</ItemGroup>

	<ItemGroup>
    	<None Include="README.md" Pack="true" PackagePath="." />
	</ItemGroup>

	<PropertyGroup>
    	<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>


</Project>
