<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Version>9.0.0-preview.15</Version>
		<PackageId>SeliseBlocks.MailDriver</PackageId>
		<Authors>SeliseBlocks</Authors>
		<Company>SeliseBlocks</Company>
		<Description>Blocks Mail Driver</Description>
		<IncludeBuildOutput>true</IncludeBuildOutput>
    	<IncludeOutputAssemblies>true</IncludeOutputAssemblies>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>Genesis, BlocksGenesis, SeliseBlocksGenesis, Email, Mail, Driver</PackageTags>
		<RepositoryUrl>https://github.com/SELISEdigitalplatforms/l1-net-blocks-mail</RepositoryUrl>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="../Mail.DomainService/Mail.DomainService.csproj" PrivateAssets="All"/>
	</ItemGroup>
	<ItemGroup>
   		<None Include="$(OutputPath)Mail.DomainService.dll" Pack="true" PackagePath="lib/net9.0/" />
	</ItemGroup>

	<ItemGroup>
    	<None Include="README.md" Pack="true" PackagePath="." />
	</ItemGroup>

	<PropertyGroup>
    	<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>


</Project>
