<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Version>9.0.0-preview.22</Version>
		<PackageId>SeliseBlocks.CaptchaDriver</PackageId>
		<Authors>SeliseBlocks</Authors>
		<Company>SeliseBlocks</Company>
		<Description>Blocks Captcha Driver</Description>
		<IncludeBuildOutput>true</IncludeBuildOutput>
    	<IncludeOutputAssemblies>true</IncludeOutputAssemblies>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>Genesis, BlocksGenesis, SeliseBlocksGenesis, Captcha , Driver</PackageTags>
		<RepositoryUrl>https://github.com/SELISEdigitalplatforms/blocks-idp-net</RepositoryUrl>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>


	<ItemGroup>
	  <ProjectReference Include="../Captcha.DomainService/Captcha.DomainService.csproj" PrivateAssets="All" />
	</ItemGroup>


	<ItemGroup>
	  <None Remove="bin\Release\net9.0\Captcha.DomainService.dll" />
	</ItemGroup>
	<ItemGroup>
   		<None Include="$(OutputPath)Captcha.DomainService.dll" Pack="true" PackagePath="lib/net9.0/" />
	</ItemGroup>

	<ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
	</ItemGroup>

	<PropertyGroup>
    	<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
</Project>
