import { API_BASES } from "@/constants/endpoint.constant";

const STORAGE_SUBPATH = "/Storage";
// const FILES_SUBPATH = "/Files";

// Storage Configuration endpoints
export const STORAGE_CONFIG_ENDPOINTS = {
  GET_CONFIGS: `${API_BASES.CLOUD_CONFIGURATION}${STORAGE_SUBPATH}/Gets`,
  SAVE_CONFIG: `${API_BASES.CLOUD_CONFIGURATION}${STORAGE_SUBPATH}/Save`,
  DELETE_CONFIG: `${API_BASES.CLOUD_CONFIGURATION}${STORAGE_SUBPATH}/Delete`,
  //TODO FE: Need to check this later, right now we will be using STORAGE_SUBPATH instead of FILES_SUBPATH
  GET_FILE: `${API_BASES.UDS}${STORAGE_SUBPATH}/GetFile`,
  DELETE_FILE: `${API_BASES.UDS}${STORAGE_SUBPATH}/DeleteFile`,
  DELETE_FOLDER: `${API_BASES.UDS}${STORAGE_SUBPATH}/DeleteFolder`,
  GET_PRESIGNED_URL: `${API_BASES.UDS}${STORAGE_SUBPATH}/GetPreSignedUrlForUpload`,
  GET_FILES_INFO: `${API_BASES.UDS}${STORAGE_SUBPATH}/GetFilesInfo`,
  UPDATE_FILE_ADDITIONAL_INFO: `${API_BASES.UDS}${STORAGE_SUBPATH}/updateFileAdditionalInfo`,
  UPLOAD_TO_LOCAL_STORAGE: `${API_BASES.UDS}${STORAGE_SUBPATH}/UploadFileToLocalStorage`,
  GET_DMS_FILE_AND_FOLDER: `${API_BASES.UDS}${STORAGE_SUBPATH}/GetDmsFileAndFolder`,
  UPLOAD_DMS_FILE: `${API_BASES.UDS}${STORAGE_SUBPATH}/UploadFile`,
  CREATE_FOLDER: `${API_BASES.UDS}${STORAGE_SUBPATH}/CreateFolder`,
  UPLOAD_PUBLIC_CERTIFICATE: `${API_BASES.UDS}${STORAGE_SUBPATH}/Certificate/UploadCertificate`,
} as const;

// Storage File endpoints
// export const STORAGE_FILE_ENDPOINTS = {
//   GET_FILE: `${API_BASES.UDS}${FILES_SUBPATH}/GetFile`,
//   DELETE_FILE: `${API_BASES.UDS}${FILES_SUBPATH}/DeleteFile`,
//   DELETE_FOLDER: `${API_BASES.UDS}${FILES_SUBPATH}/DeleteFolder`,
//   GET_PRESIGNED_URL: `${API_BASES.UDS}${FILES_SUBPATH}/GetPreSignedUrlForUpload`,
//   GET_FILES_INFO: `${API_BASES.UDS}${FILES_SUBPATH}/GetFilesInfo`,
//   UPDATE_FILE_ADDITIONAL_INFO: `${API_BASES.UDS}${FILES_SUBPATH}/updateFileAdditionalInfo`,
//   UPLOAD_TO_LOCAL_STORAGE: `${API_BASES.UDS}${FILES_SUBPATH}/UploadFileToLocalStorage`,
//   GET_DMS_FILE_AND_FOLDER: `${API_BASES.UDS}${FILES_SUBPATH}/GetDmsFileAndFolder`,
//   UPLOAD_DMS_FILE: `${API_BASES.UDS}${FILES_SUBPATH}/UploadFile`,
//   CREATE_FOLDER: `${API_BASES.UDS}${FILES_SUBPATH}/CreateFolder`,
//   UPLOAD_PUBLIC_CERTIFICATE: `${API_BASES.UDS}/Certificate/UploadCertificate`,
// } as const;
